cmake_minimum_required(VERSION 3.16)

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "ARM")

set(P2K_EP1_TOOLCHAIN_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

if(ARM_MODE STREQUAL "Thumb")
	set(CMAKE_C_COMPILER "${P2K_EP1_TOOLCHAIN_ROOT}/tcc")
	set(CMAKE_CXX_COMPILER "${P2K_EP1_TOOLCHAIN_ROOT}/tcpp")
elseif(ARM_MODE STREQUAL "ARM")
	set(CMAKE_C_COMPILER "${P2K_EP1_TOOLCHAIN_ROOT}/armcc")
	set(CMAKE_CXX_COMPILER "${P2K_EP1_TOOLCHAIN_ROOT}/armcpp")
else()
	message(FATAL_ERROR "Please set '$ARM_MODE' to 'Thumb' or 'ARM'!")
endif()
set(CMAKE_ASM_COMPILER "${P2K_EP1_TOOLCHAIN_ROOT}/armasm")
set(CMAKE_AR "${P2K_EP1_TOOLCHAIN_ROOT}/armar")
set(CMAKE_C_LINK_EXECUTABLE "${P2K_EP1_TOOLCHAIN_ROOT}/armlink")
set(CMAKE_CXX_LINK_EXECUTABLE "${P2K_EP1_TOOLCHAIN_ROOT}/armlink")
if(WIN32)
	set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}.exe")
	set(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}.exe")
	set(CMAKE_ASM_COMPILER "${CMAKE_ASM_COMPILER}.exe")
	set(CMAKE_AR "${CMAKE_AR}.exe")
	set(CMAKE_C_LINK_EXECUTABLE "${CMAKE_C_LINK_EXECUTABLE}.exe")
	set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE}.exe")
endif()

set(CMAKE_C_COMPILER_ID "ADS")
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_ID "ADS")
set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
#set(CMAKE_ASM_COMPILER_ID "ARMCC")
set(CMAKE_ASM_COMPILER_ID "ADS")

set(P2K_DIRECTORY_HEADERS_SDK "${P2K_EP1_TOOLCHAIN_ROOT}/SDK")
set(P2K_DIRECTORY_HEADERS_LIBRARIES "${P2K_EP1_TOOLCHAIN_ROOT}/SDK/lib")
set(P2K_DIRECTORY_LIBRARIES "${P2K_EP1_TOOLCHAIN_ROOT}/lib")

set(P2K_GENERAL_DEFINES_FLAGS "-D__P2K__ -DEP1")
set(P2K_GENERAL_OPTIMIZATION_FLAGS "-O2")
set(P2K_LIB_NAME "Lib")
set(P2K_LIB_FILE "${P2K_LIB_NAME}.o")

if(ARM_MODE STREQUAL "Thumb")
	set(P2K_GENERAL_C_FLAGS "-bigend -apcs /interwork")
	set(P2K_GENERAL_CXX_FLAGS "-bigend -apcs /interwork")
	set(P2K_GENERAL_ASM_FLAGS "-32 -bi -apcs /interwork")
	set(P2K_GENERAL_C_LINK_FLAGS
		"-nolocals -reloc -first ${P2K_LIB_FILE}(${P2K_LIB_NAME}) ${P2K_DIRECTORY_LIBRARIES}/${P2K_LIB_FILE}")
	set(P2K_GENERAL_CXX_LINK_FLAGS
		"-nolocals -reloc -first ${P2K_LIB_FILE}(${P2K_LIB_NAME}) ${P2K_DIRECTORY_LIBRARIES}/${P2K_LIB_FILE}")
elseif(ARM_MODE STREQUAL "ARM")
	set(P2K_GENERAL_C_FLAGS "-bigend -apcs /interwork")
	set(P2K_GENERAL_CXX_FLAGS "-bigend -apcs /interwork")
	set(P2K_GENERAL_ASM_FLAGS "-32 -bi -apcs /interwork")
	set(P2K_GENERAL_C_LINK_FLAGS
		"-nolocals -reloc -first ${P2K_LIB_FILE}(${P2K_LIB_NAME}) ${P2K_DIRECTORY_LIBRARIES}/${P2K_LIB_FILE}")
	set(P2K_GENERAL_CXX_LINK_FLAGS
		"-nolocals -reloc -first ${P2K_LIB_FILE}(${P2K_LIB_NAME}) ${P2K_DIRECTORY_LIBRARIES}/${P2K_LIB_FILE}")
else()
	message(FATAL_ERROR "Please set '$ARM_MODE' to 'Thumb' or 'ARM'!")
endif()

set(CMAKE_C_FLAGS "${P2K_GENERAL_DEFINES_FLAGS} ${P2K_GENERAL_OPTIMIZATION_FLAGS} ${P2K_GENERAL_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${P2K_GENERAL_DEFINES_FLAGS} ${P2K_GENERAL_OPTIMIZATION_FLAGS} ${P2K_GENERAL_CXX_FLAGS}")
set(CMAKE_ASM_FLAGS "${P2K_GENERAL_ASM_FLAGS}")

set(CMAKE_C_LINK_EXECUTABLE
	"${CMAKE_C_LINK_EXECUTABLE} ${P2K_GENERAL_C_LINK_FLAGS} <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>.elf")
set(CMAKE_CXX_LINK_EXECUTABLE
	"${CMAKE_CXX_LINK_EXECUTABLE} ${P2K_GENERAL_CXX_LINK_FLAGS} <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> -o <TARGET>.elf")

set(CMAKE_C_CREATE_STATIC_LIBRARY "<CMAKE_AR> --create -cr <TARGET> <OBJECTS>")
set(CMAKE_CXX_CREATE_STATIC_LIBRARY "<CMAKE_AR> --create -cr <TARGET> <OBJECTS>")

set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

include_directories("${P2K_DIRECTORY_HEADERS_SDK}" "${P2K_DIRECTORY_HEADERS_LIBRARIES}")
