cmake_minimum_required(VERSION 3.16)

set(CMAKE_SYSTEM_NAME "Generic")
set(CMAKE_SYSTEM_PROCESSOR "M*CORE")

set(P2K_EM1_TOOLCHAIN_ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

set(CMAKE_C_COMPILER "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-gcc")
set(CMAKE_CXX_COMPILER "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-g++")
#set(CMAKE_ASM_COMPILER "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-as")
set(CMAKE_ASM_COMPILER "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-gcc")
set(CMAKE_AR "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-ar")
set(CMAKE_C_LINK_EXECUTABLE "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-ld")
set(CMAKE_CXX_LINK_EXECUTABLE "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/bin/mcore-elf-ld")
if(WIN32)
	set(CMAKE_C_COMPILER "${CMAKE_C_COMPILER}.exe")
	set(CMAKE_CXX_COMPILER "${CMAKE_CXX_COMPILER}.exe")
	set(CMAKE_ASM_COMPILER "${CMAKE_ASM_COMPILER}.exe")
	set(CMAKE_AR "${CMAKE_AR}.exe")
	set(CMAKE_C_LINK_EXECUTABLE "${CMAKE_C_LINK_EXECUTABLE}.exe")
	set(CMAKE_CXX_LINK_EXECUTABLE "${CMAKE_CXX_LINK_EXECUTABLE}.exe")
endif()

set(CMAKE_C_COMPILER_ID "GNU")
set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_ID "GNU")
set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)

set(P2K_DIRECTORY_HEADERS_SDK "${P2K_EM1_TOOLCHAIN_ROOT}/SDK")
set(P2K_DIRECTORY_HEADERS_LIBRARIES "${P2K_EM1_TOOLCHAIN_ROOT}/SDK/lib")
set(P2K_DIRECTORY_LIBRARIES "${P2K_EM1_TOOLCHAIN_ROOT}/GCC_MCore/mcore-elf/lib")

set(P2K_GENERAL_DEFINES_FLAGS "-D__P2K__ -DEM1")
set(P2K_GENERAL_OPTIMIZATION_FLAGS "-O2")
set(P2K_LIB_C "libc.a")

set(P2K_GENERAL_C_FLAGS "-fshort-wchar -mbig-endian -nostdinc -m340 -fomit-frame-pointer -nostdlib -fno-builtin")
set(P2K_GENERAL_CXX_FLAGS "-fshort-wchar -mbig-endian -nostdinc -m340 -fomit-frame-pointer -nostdlib -fno-builtin")
set(P2K_GENERAL_ASM_FLAGS "-fshort-wchar -mbig-endian -nostdinc -m340 -fomit-frame-pointer -nostdlib -fno-builtin")
set(P2K_GENERAL_C_LINK_FLAGS "${P2K_GENERAL_OPTIMIZATION_FLAGS} -dn -r -no-bss-init -z muldefs")
set(P2K_GENERAL_CXX_LINK_FLAGS "${P2K_GENERAL_OPTIMIZATION_FLAGS} -dn -r -no-bss-init -z muldefs")
set(P2K_GENERAL_LINKER_SCRIPT "-T${P2K_DIRECTORY_LIBRARIES}/linker_elf.ld")
#set(P2K_GENERAL_LIBRARIES "${P2K_DIRECTORY_LIBRARIES}/${P2K_LIB_C}")

set(CMAKE_C_FLAGS "${P2K_GENERAL_DEFINES_FLAGS} ${P2K_GENERAL_OPTIMIZATION_FLAGS} ${P2K_GENERAL_C_FLAGS}")
set(CMAKE_CXX_FLAGS "${P2K_GENERAL_DEFINES_FLAGS} ${P2K_GENERAL_OPTIMIZATION_FLAGS} ${P2K_GENERAL_CXX_FLAGS}")
set(CMAKE_ASM_FLAGS "${P2K_GENERAL_ASM_FLAGS}")

set(CMAKE_C_LINK_EXECUTABLE
	"${CMAKE_C_LINK_EXECUTABLE} ${P2K_GENERAL_C_LINK_FLAGS} <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> ${P2K_GENERAL_LIBRARIES} ${P2K_GENERAL_LINKER_SCRIPT} -o <TARGET>.elf")
set(CMAKE_CXX_LINK_EXECUTABLE
	"${CMAKE_CXX_LINK_EXECUTABLE} ${P2K_GENERAL_CXX_LINK_FLAGS} <CMAKE_CXX_LINK_FLAGS> <LINK_FLAGS> <OBJECTS> <LINK_LIBRARIES> ${P2K_GENERAL_LIBRARIES} ${P2K_GENERAL_LINKER_SCRIPT} -o <TARGET>.elf")

#set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <INCLUDES> <FLAGS> -o <OBJECT> <SOURCE>")

include_directories("${P2K_DIRECTORY_HEADERS_SDK}" "${P2K_DIRECTORY_HEADERS_LIBRARIES}")
