#ifndef __ERROR_CODES_H__
#define __ERROR_CODES_H__

enum {
	LDR_RESULT_OK						=	0x0,
	LDR_RESULT_FAIL						=	0x1,
	LDR_RESULT_ERROR_BAD_ARGUMENT		=	0x2,
	LDR_RESULT_ERROR_RETURN_NULL		=	0x3,

	LDR_RESULT_ERROR_MEM				=	0x0100,
	LDR_RESULT_ERROR_MEM_ALLOC			=	LDR_RESULT_ERROR_MEM + 0x01,

	LDR_RESULT_ERROR_FILE				=	0x0200,
	LDR_RESULT_ERROR_FILE_NOT_EXIST		=	LDR_RESULT_ERROR_FILE + 0x01,
	LDR_RESULT_ERROR_FILE_OPEN			=	LDR_RESULT_ERROR_FILE + 0x02,
	LDR_RESULT_ERROR_FILE_READ			=	LDR_RESULT_ERROR_FILE + 0x03,
	LDR_RESULT_ERROR_FILE_SEEK			=	LDR_RESULT_ERROR_FILE + 0x04,

	LDR_RESULT_ERROR_FORMAT				=	0x0300,
	LDR_RESULT_ERROR_PHNUM_MUCH			=	LDR_RESULT_ERROR_FORMAT + 0x01,
	LDR_RESULT_ERROR_DYNNUM_MUCH		=	LDR_RESULT_ERROR_FORMAT + 0x02,
	LDR_RESULT_ERROR_EABI_VERSION2		=	LDR_RESULT_ERROR_FORMAT + 0x03,

	LDR_RESULT_ERROR_LIB				=	0x0400,
	LDR_RESULT_ERROR_LIB_MUCH			=	LDR_RESULT_ERROR_LIB + 0x01,
	LDR_RESULT_ERROR_LIB_NOT_FIND		=	LDR_RESULT_ERROR_LIB + 0x02,
	LDR_RESULT_ERROR_LIB_INIT_FAILED	=	LDR_RESULT_ERROR_LIB + 0x03,
	LDR_RESULT_ERROR_LIB_FINI_FAILED	=	LDR_RESULT_ERROR_LIB + 0x04,

	LDR_RESULT_ERROR_RELOC				=	0x0500,
	LDR_RESULT_ERROR_RELOC_NOT_FIND		=	LDR_RESULT_ERROR_RELOC + 0x01,
	LDR_RESULT_ERROR_RELOC_UNK_TYPE		=	LDR_RESULT_ERROR_RELOC + 0x02,

	LDR_RESULT_ERROR_SYM_NOT_FIND		=	0x0600,
	
	LDR_RESULT_ERROR_MAX
	
};

typedef UINT32 LDR_RESULT_CODE;

#endif /* __ERROR_CODES_H__ */
